"""add daily_digests

Revision ID: 2f694f47e108
Revises: 8e6af48d3753
Create Date: 2026-01-09 04:45:31.313646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f694f47e108'
down_revision: Union[str, Sequence[str], None] = '8e6af48d3753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'daily_digests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('journal', sa.String(length=100), nullable=False),
        sa.Column('code', sa.String(length=30), nullable=True),
        sa.Column('category', sa.String(length=100), nullable=True),
        sa.Column('title', sa.String(length=300), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('date', 'journal', name='uq_daily_digest_date_journal')
    )
    with op.batch_alter_table('daily_digests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_digests_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_digests_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_digests_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_digests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_digests_journal'), ['journal'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_digests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_digests_journal'))
        batch_op.drop_index(batch_op.f('ix_daily_digests_id'))
        batch_op.drop_index(batch_op.f('ix_daily_digests_date'))
        batch_op.drop_index(batch_op.f('ix_daily_digests_code'))
        batch_op.drop_index(batch_op.f('ix_daily_digests_category'))

    op.drop_table('daily_digests')
    # ### end Alembic commands ###
