# 1) HTTP：给证书校验放行 + 其他全部跳转 HTTPS
server {
    listen 80;
    server_name matflow.top;

    return 301 https://$host$request_uri;
}

# 2) HTTPS：真正提供前端与 /api/ 反代 + IP 白名单
server {
    listen 443 ssl http2;
    listen [::]:443 ssl;
    server_name matflow.top;

    client_max_body_size 10240m;

    ssl_certificate     /etc/nginx/ssl/matflow.top/matflow.top.pem;
    ssl_certificate_key /etc/nginx/ssl/matflow.top/matflow.top.key;

    ssl_protocols TLSv1.2 TLSv1.3;  # 只允许安全的 TLS 版本

    # 加密套件（优化版）
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers on;

    # --- IP 白名单（写在最上面，最后 deny all）---
    allow 127.0.0.1;
    allow ::1;

    allow 114.214.207.67;  # 物质楼B 1402
    allow 114.214.197.96;  # 物质楼B 1407
    allow 114.214.196.227; # Pwjb
    allow 114.214.200.167; # Pwjb
    allow 114.214.200.115; # Pcheyx
    allow 114.214.200.139; # Phflv
    allow 114.214.201.221; # Pzxp
    allow 114.214.196.32;  # Pwyt
    allow 114.214.203.186; # Plyf
    allow 114.214.207.227; # Pxpb
    allow 114.214.207.205; # Pliyuxuan
    allow 114.214.196.22;  # Pzhangkai
    allow 114.214.196.195; # Pjzh
    allow 114.214.205.83;  # Psunmiao
    allow 114.214.196.34;  # Pgyh
    allow 211.86.0.0/16;   # 校园网段(开openvpn时使用)
    allow 210.45.118.14;   # 科大校园 Wi-Fi（移动端当前出口）

    allow 222.195.94.37;   # node21

    deny all;
    # --- IP 白名单结束 ---

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        client_max_body_size 10240m;
        resolver 127.0.0.11 valid=10s ipv6=off;

        set $upstream http://backend:4000;
        proxy_pass $upstream;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_buffering off;
        proxy_request_buffering off;

        proxy_connect_timeout 60s;
        proxy_send_timeout 1800s;
        proxy_read_timeout 1800s;
        send_timeout 1800s;
    }
}
