import { useEffect, useRef, useState } from 'react';
import { colorForElement } from '../../../utils/elementColors';

function addVectors(left, right) {
  return { x: left.x + right.x, y: left.y + right.y, z: left.z + right.z };
}

function scaleVector(vector, scale) {
  return { x: vector.x * scale, y: vector.y * scale, z: vector.z * scale };
}

function toVector(value) {
  return {
    x: Number(value?.[0]) || 0,
    y: Number(value?.[1]) || 0,
    z: Number(value?.[2]) || 0,
  };
}

function buildXyz(structure) {
  const positions = structure.positions || [];
  const symbols = structure.symbols || [];
  const lines = [String(positions.length), 'generated by LMateLab'];
  positions.forEach((position, index) => {
    lines.push(`${symbols[index] || 'X'} ${position[0]} ${position[1]} ${position[2]}`);
  });
  return `${lines.join('\n')}\n`;
}

function drawCellAndAxes(viewer, cell) {
  if (!Array.isArray(cell) || cell.length !== 3) return;
  const origin = { x: 0, y: 0, z: 0 };
  const a = toVector(cell[0]);
  const b = toVector(cell[1]);
  const c = toVector(cell[2]);
  const ab = addVectors(a, b);
  const ac = addVectors(a, c);
  const bc = addVectors(b, c);
  const abc = addVectors(ab, c);
  const edges = [
    [origin, a], [origin, b], [origin, c],
    [a, ab], [a, ac], [b, ab], [b, bc], [c, ac], [c, bc],
    [ab, abc], [ac, abc], [bc, abc],
  ];
  edges.forEach(([start, end]) => viewer.addLine({ start, end, color: '#344054', linewidth: 2 }));

  const axes = [
    ['a', a, '#d92d20'],
    ['b', b, '#039855'],
    ['c', c, '#1570ef'],
  ];
  axes.forEach(([label, vector, color]) => {
    const end = scaleVector(vector, 0.25);
    viewer.addArrow({ start: origin, end, color, radius: 0.06, radiusRatio: 1.6, mid: 0.9 });
    viewer.addLabel(label, {
      position: scaleVector(end, 1.1),
      fontColor: color,
      backgroundOpacity: 0,
      fontSize: 15,
    });
  });
}

export default function VaspStructureViewer({ structure }) {
  const hostRef = useRef(null);
  const [renderState, setRenderState] = useState({ status: 'loading', message: '' });
  const positions = Array.isArray(structure?.positions) ? structure.positions : [];

  useEffect(() => {
    if (!hostRef.current || positions.length === 0) return undefined;
    let alive = true;
    let viewer = null;
    let resizeObserver = null;
    const host = hostRef.current;

    (async () => {
      try {
        const threeDmolModule = await import('3dmol');
        if (!alive) return;
        const threeDmol = threeDmolModule.default?.createViewer
          ? threeDmolModule.default
          : threeDmolModule;
        if (typeof threeDmol.createViewer !== 'function') {
          throw new Error('3Dmol createViewer is unavailable');
        }

        host.innerHTML = '';
        viewer = threeDmol.createViewer(host, { backgroundColor: '#ffffff' });
        viewer.addModel(buildXyz(structure), 'xyz');
        const elements = [...new Set((structure.symbols || []).filter(Boolean))];
        if (elements.length === 0) {
          viewer.setStyle({}, { stick: { radius: 0.18 }, sphere: { scale: 0.25 } });
        } else {
          elements.forEach((element) => {
            const color = colorForElement(element);
            viewer.setStyle(
              { elem: element },
              { stick: { radius: 0.18, color }, sphere: { scale: 0.25, color } },
            );
          });
        }
        drawCellAndAxes(viewer, structure.cell);
        if (typeof viewer.setProjection === 'function') viewer.setProjection('orthographic');
        viewer.zoomTo();
        viewer.render();

        resizeObserver = new ResizeObserver(() => {
          if (!viewer) return;
          viewer.resize();
          viewer.render();
        });
        resizeObserver.observe(host);
        setRenderState({ status: 'ready', message: '' });
      } catch (error) {
        if (alive) setRenderState({ status: 'error', message: String(error?.message || error) });
      }
    })();

    return () => {
      alive = false;
      resizeObserver?.disconnect();
      if (viewer && typeof viewer.clear === 'function') viewer.clear();
      host.innerHTML = '';
    };
  }, [positions.length, structure]);

  if (positions.length === 0) {
    return <div className="vasp-structure-viewer is-message">暂无可渲染的结构坐标</div>;
  }

  return (
    <div className="vasp-structure-viewer">
      <div className="vasp-viewer-canvas" ref={hostRef} />
      {renderState.status === 'loading' ? (
        <div className="vasp-viewer-state">正在加载结构查看器…</div>
      ) : null}
      {renderState.status === 'error' ? (
        <div className="vasp-viewer-state is-error">结构渲染失败：{renderState.message}</div>
      ) : null}
    </div>
  );
}
