export const CATEGORY_COLOR = {
  alkali: "#8BC34A",
  alkaline_earth: "#C5E1A5",
  transition: "#90CAF9",
  post_transition: "#B0BEC5",
  metalloid: "#FFCC80",
  nonmetal: "#A5D6A7",
  halogen: "#EF9A9A",
  noble_gas: "#B39DDB",
  lanthanide: "#FFE082",
  actinide: "#FFCC80",
  unknown: "#ECEFF1",
};

export const CATEGORY_BY_SYMBOL = {
  H: "nonmetal",
  C: "nonmetal",
  N: "nonmetal",
  O: "nonmetal",
  P: "nonmetal",
  S: "nonmetal",
  Se: "nonmetal",

  F: "halogen",
  Cl: "halogen",
  Br: "halogen",
  I: "halogen",
  At: "halogen",
  Ts: "halogen",

  He: "noble_gas",
  Ne: "noble_gas",
  Ar: "noble_gas",
  Kr: "noble_gas",
  Xe: "noble_gas",
  Rn: "noble_gas",
  Og: "noble_gas",

  Li: "alkali",
  Na: "alkali",
  K: "alkali",
  Rb: "alkali",
  Cs: "alkali",
  Fr: "alkali",

  Be: "alkaline_earth",
  Mg: "alkaline_earth",
  Ca: "alkaline_earth",
  Sr: "alkaline_earth",
  Ba: "alkaline_earth",
  Ra: "alkaline_earth",

  B: "metalloid",
  Si: "metalloid",
  Ge: "metalloid",
  As: "metalloid",
  Sb: "metalloid",
  Te: "metalloid",

  Al: "post_transition",
  Ga: "post_transition",
  In: "post_transition",
  Tl: "post_transition",
  Sn: "post_transition",
  Pb: "post_transition",
  Bi: "post_transition",
  Po: "post_transition",

  Sc: "transition",
  Ti: "transition",
  V: "transition",
  Cr: "transition",
  Mn: "transition",
  Fe: "transition",
  Co: "transition",
  Ni: "transition",
  Cu: "transition",
  Zn: "transition",
  Y: "transition",
  Zr: "transition",
  Nb: "transition",
  Mo: "transition",
  Tc: "transition",
  Ru: "transition",
  Rh: "transition",
  Pd: "transition",
  Ag: "transition",
  Cd: "transition",
  Hf: "transition",
  Ta: "transition",
  W: "transition",
  Re: "transition",
  Os: "transition",
  Ir: "transition",
  Pt: "transition",
  Au: "transition",
  Hg: "transition",
  Rf: "transition",
  Db: "transition",
  Sg: "transition",
  Bh: "transition",
  Hs: "transition",
  Mt: "transition",
  Ds: "transition",
  Rg: "transition",
  Cn: "transition",

  La: "lanthanide",
  Ce: "lanthanide",
  Pr: "lanthanide",
  Nd: "lanthanide",
  Pm: "lanthanide",
  Sm: "lanthanide",
  Eu: "lanthanide",
  Gd: "lanthanide",
  Tb: "lanthanide",
  Dy: "lanthanide",
  Ho: "lanthanide",
  Er: "lanthanide",
  Tm: "lanthanide",
  Yb: "lanthanide",
  Lu: "lanthanide",

  Ac: "actinide",
  Th: "actinide",
  Pa: "actinide",
  U: "actinide",
  Np: "actinide",
  Pu: "actinide",
  Am: "actinide",
  Cm: "actinide",
  Bk: "actinide",
  Cf: "actinide",
  Es: "actinide",
  Fm: "actinide",
  Md: "actinide",
  No: "actinide",
  Lr: "actinide",

  Nh: "post_transition",
  Fl: "post_transition",
  Mc: "post_transition",
  Lv: "post_transition",
};
