"""add papers_json to daily_digests

Revision ID: 107026465e68
Revises: 261defce72b5
Create Date: 2026-01-09 19:36:26.249826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107026465e68'
down_revision: Union[str, Sequence[str], None] = '261defce72b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ✅ 先修旧数据：把 created_at 为 NULL 的行补齐
    # SQLite 支持 CURRENT_TIMESTAMP（UTC 风格的文本时间）
    op.execute("UPDATE daily_digests SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")

    # ✅ 再做 batch 改表：新增列并给 server_default，避免复制/插入时触发 NOT NULL 问题
    with op.batch_alter_table("daily_digests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("papers_json", sa.Text(), nullable=False, server_default="[]")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_digests', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('papers_json')

    # ### end Alembic commands ###
