"""init digest

Revision ID: 261defce72b5
Revises: 
Create Date: 2026-01-09 13:48:08.825522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261defce72b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('journal', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'journal', name='uq_daily_digest_date_journal')
    )
    with op.batch_alter_table('daily_digests', schema=None) as batch_op:
        batch_op.create_index('ix_daily_digests_category', ['category'], unique=False)
        batch_op.create_index('ix_daily_digests_code', ['code'], unique=False)
        batch_op.create_index('ix_daily_digests_date', ['date'], unique=False)
        batch_op.create_index('ix_daily_digests_journal', ['journal'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    with op.batch_alter_table('daily_digests', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_digests_journal')
        batch_op.drop_index('ix_daily_digests_date')
        batch_op.drop_index('ix_daily_digests_code')
        batch_op.drop_index('ix_daily_digests_category')

    op.drop_table('daily_digests')
    # ### end Alembic commands ###
